spring.application.name=crud-tarefas-com-spring
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_HOST}
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

